Homebrew Update for Mac
 3.0.0 - Homebrew supports Mac M1

The command which worked on my Mac M1 was  "arch -arm64 brew install dapr/tap/dapr-cli"

Here is the output 

arch -arm64 brew install dapr/tap/dapr-cli
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.17.2
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:b0a1686c5c5ba668e78a97d66567e9d007f7d2a0c9b1a53e79841e3736d729e6
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:b0a1686c5c5ba668e78a97d66567e9d007f7d2a0c9b1a53e79841e3736d729e6?se=2021-10-20T18%3A00%3A00Z&sig=yRfOG5pLjci12lOR2LOurCSGZjgWHgTKSV00%2B8Ys2PI%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/make/manifests/4.3-1
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/make/blobs/sha256:eab3fbc3688aecec0fe90b8d0fe3cb7beb84ed773ba0411fc2f855c66deaf882
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:eab3fbc3688aecec0fe90b8d0fe3cb7beb84ed773ba0411fc2f855c66deaf882?se=2021-10-20T18%3A05%3A00Z&sig=YsB%2FxVvM7Q%2BjIVUXWwBGgGYPo%2F7lYMM5RohWXPKe3gY%3D&sp=r&spr=https&sr=b&sv=2019-12-12
######################################################################## 100.0%
==> Downloading https://github.com/dapr/cli/archive/v1.4.0.tar.gz
==> Downloading from https://codeload.github.com/dapr/cli/tar.gz/v1.4.0
#-#O=#  #                                                                     
==> Installing dapr-cli from dapr/tap
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.0.

==> Installing dependencies for dapr/tap/dapr-cli: go and make
==> Installing dapr/tap/dapr-cli dependency: go
==> Pouring go--1.17.2.arm64_big_sur.bottle.tar.gz
🍺  /opt/homebrew/Cellar/go/1.17.2: 10,814 files, 564.3MB
==> Installing dapr/tap/dapr-cli dependency: make
==> Pouring make--4.3.arm64_big_sur.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/make/4.3: 15 files, 1MB
==> Installing dapr/tap/dapr-cli
==> make REL_VERSION=1.4.0
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - dist/darwin_amd64/release/dapr


The brew formula needs to be corrected however.